# Generated by Django 5.0.8 on 2024-08-10 07:01

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client_id',
            field=models.CharField(default=123456789, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=django_cryptography.fields.encrypt(models.CharField(default=123456789, max_length=255)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp',
            field=django_cryptography.fields.encrypt(models.CharField(default=123456789, max_length=255)),
            preserve_default=False,
        ),
    ]
