# Generated by Django 5.0.8 on 2024-08-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_customuser_client_id_customuser_pin_customuser_totp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='totp',
            new_name='token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='apiKey',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
    ]
