# Generated by Django 5.0.8 on 2024-08-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_totp_customuser_token_customuser_apikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='client_id',
            new_name='clientID',
        ),
    ]
