# Generated by Django 5.0.8 on 2024-08-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_client_id_customuser_clientid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradingsymbol', models.CharField(max_length=20)),
                ('transactiontype', models.CharField(max_length=4)),
                ('exchange', models.CharField(max_length=10)),
                ('ordertype', models.CharField(max_length=10)),
                ('producttype', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('orderid', models.CharField(max_length=30)),
            ],
        ),
    ]
