# Generated by Django 5.0.8 on 2024-08-11 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_orderrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
