# Generated by Django 5.0.8 on 2024-08-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_customuser_feedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jwtToken',
            field=models.CharField(default=125882241, max_length=255),
            preserve_default=False,
        ),
    ]
